### ISSUE TITLE
A bit too light 

### ISSUE THREAD

**Issue by kmalkic** [ustwo/baseviewcontroller-swift#2]
Feel like a convenient way of not having to repeat loadView, setupView and setupAccessibility, but having to set some pod or integrating the framework for just 3 methods look like i could leave with rewriting my own thing.
I'm keen of generics, and i'm sure there would be new ideas to be implemented for saving thousands of poor ios souls. :)

**Comment by ghost** [comment]
Yes, it's just as easy to drop in the single file.

The advantage to having it as a Pod would be to:
- More quickly jumpstart a new project.
- Get updates automatically as improvements from others are made.
- Eventually we can add other types of "base view controllers" as subspecs so that you can get a whole collection of them. Right now we're just starting with one (I have some good ones for searchable table view controllers).
